### ISSUE TITLE
Open Telemetry Custom Collector Service

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1214]
From #1176

The opentelemetry-collector service/service.go will need to be adapted to start with an otlpreceiver, that receives the data plumbed from sinker service.

insert image here

- POC investigation points
1. How to pass Agent ID in OTLP payload
2. Create Pipeline in Runtime
3. Multiple TSDB exporters

**Comment by lpegoraro** [comment]
Alright, so #1484 will create the new orb-collector or orb-col for short

Definition of Ready

- [x] Create Otel-Col main function in cmd #1484
- [x] Create Otel-Col package with functionalities to import new components from `github.com/open-telemetry/opentelemetry-collector-contrib`, `go.opentelemetry.io/collector`  #1484
- [ ] Create Orb-Helm and integrate with Orb Control Plane cluster PR TBD
- [ ] Create Receiver to receive data from Orb-Sinker // In progress in #1484

**Comment by lpegoraro** [comment]
@weyrick @rboucher-ns1 
What do you guys prefer? 
Merge the DraftPR and close this since it is the base of the development of the inner components, even without the components. But we won't be able to run this service until all components are working. 

Or leave in Code Review until all components inside are working, and we only then close this issue?

**Comment by lpegoraro** [comment]
Closing this, since it was redesigned
